#ifndef PIECE_LINUX_HARDWARE_H
#define PIECE_LINUX_HARDWARE_H

#define GPIO_DIGITAL_OUT 1
#define GPIO_DIGITAL_IN 2
#define GPIO_ANALOG_OUT 4
#define GPIO_ANALOG_IN 8
#define GPIO_GENERAL_IO 15
#define GPIO_INTERRUPT 16
#define GPIO_SERIAL_RX0 32
#define GPIO_SERIAL_TX0 64

#define GPIO_PIN_COUNT 17
#define GPIO_PIN_CAPABILITY_1 GPIO_GENERAL_IO | GPIO_SERIAL_TX0
#define GPIO_PIN_CAPABILITY_2 GPIO_GENERAL_IO
#define GPIO_PIN_CAPABILITY_3 GPIO_GENERAL_IO | GPIO_SERIAL_RX0
#define GPIO_PIN_CAPABILITY_4 GPIO_GENERAL_IO
#define GPIO_PIN_CAPABILITY_5 GPIO_GENERAL_IO
#define GPIO_PIN_CAPABILITY_6 GPIO_GENERAL_IO
#define GPIO_PIN_CAPABILITY_7 GPIO_GENERAL_IO
#define GPIO_PIN_CAPABILITY_8 GPIO_GENERAL_IO
#define GPIO_PIN_CAPABILITY_9 GPIO_GENERAL_IO
#define GPIO_PIN_CAPABILITY_10 GPIO_GENERAL_IO
#define GPIO_PIN_CAPABILITY_11 GPIO_GENERAL_IO
#define GPIO_PIN_CAPABILITY_12 GPIO_GENERAL_IO
#define GPIO_PIN_CAPABILITY_13 GPIO_GENERAL_IO
#define GPIO_PIN_CAPABILITY_14 GPIO_GENERAL_IO
#define GPIO_PIN_CAPABILITY_15 GPIO_GENERAL_IO
#define GPIO_PIN_CAPABILITY_16 GPIO_GENERAL_IO
#define GPIO_PIN_CAPABILITY_17 GPIO_GENERAL_IO

#endif //PIECE_LINUX_HARDWARE_H